apache:
  image: eeacms/reportek-apache
  restart: always
  ports:
  - "80:80"
  - "443:443"
  links:
  - haproxy:haproxy
  env_file:
  - envs/apache-sandbox.env

instance1:
  image: eeacms/reportek-cdr
  restart: always
  links:
  - zeoserver
  - localconv:converter
  - redis:redisdeploy

instance2:
  image: eeacms/reportek-cdr
  restart: always
  links:
  - zeoserver
  - localconv:converter
  - redis:redisdeploy

haproxy:
  image: eeacms/haproxy
  restart: always
  links:
  - instance1
  - instance2
  environment:
    COOKIES_ENABLED: "true"
    BACKENDS_PORT: 8080

zeoserver:
  image: eeacms/zeoserver
  restart: always
  volumes_from:
  - data

localconv:
  image: eeacms/reportek-local-converters
  restart: always

cron:
  image: eeacms/reportek-cron
  restart: always
  env_file:
  - envs/cron-sandbox.env

redis:
  image: redis:3
  restart: always
  volumes_from:
  - redisdata

data:
  image: busybox
  volumes:
  - /opt/zeoserver/var/filestorage
  - /opt/zeoserver/var/blobstorage
  command: chown -R 500:500 /opt/zeoserver/var

redisdata:
  image: busybox
  volumes:
  - /data
  command: chown -R 999:999 /data
