apache:
  image: eeacms/reportek-apache:development
  restart: always
  ports:
  - "80:80"
  - "443:443"
  links:
  - haproxy:haproxy
  env_file:
  - envs/apache-dev.env

instance1:
  image: eeacms/reportek-cdr:development
  restart: always
  links:
  - zeoserver
  - localconv:converter
  - redis:redisdeploy
  environment:
  - ALWAYS_CHECKOUT=true
  - SOURCE_Products_Reportek=git https://github.com/eea/Products.Reportek branch=development

instance2:
  image: eeacms/reportek-cdr:development
  restart: always
  links:
  - zeoserver
  - localconv:converter
  - redis:redisdeploy
  environment:
  - ALWAYS_CHECKOUT=true
  - SOURCE_Products_Reportek=git https://github.com/eea/Products.Reportek branch=development

haproxy:
  image: eeacms/haproxy
  restart: always
  links:
  - instance1
  - instance2
  environment:
    COOKIES_ENABLED: true
    BACKENDS_PORT: 8080

zeoserver:
  image: eeacms/zeoserver
  restart: always
  volumes_from:
  - data

localconv:
  image: eeacms/reportek-local-converters
  restart: always

cron:
  image: eeacms/reportek-cron:development
  restart: always
  env_file:
  - envs/cron-dev.env

redis:
  image: redis:3
  restart: always
  volumes_from:
  - redisdata

data:
  image: busybox
  volumes:
  - /opt/zeoserver/var/filestorage
  - /opt/zeoserver/var/blobstorage
  command: chown -R 500:500 /opt/zeoserver/var

redisdata:
  image: busybox
  volumes:
  - /data
  command: chown -R 999:999 /data
